environment: development
namespace: default
serviceName: my-service
imageTag: abc123
secrets:
  enabled: true
  values: [KEYCLOAK_PASSWORD, KEYCLOAK_USER, POSTGRES_DB, KC_DB_URL, POSTGRES_PASSWORD, POSTGRES_USER ]
  #VALID VALUES - services, tools
  applicationType: services
configmap:
  enabled: true
  values:
    ASPNETCORE_ENVIRONMENT: Development
volumes:
  enabled: true
kafka:
  enabled: true
  keys: [KAFKA_BOOTSTRAP, KAFKA_CA_CERT_PATH, KAFKA_USER_CERT_PATH, KAFKA_USER_KEY_CERT_PATH]
  kafkaUser: kafka-user
  server: kafka-development-kafka-bootstrap.kafka-development:9093
deployment:
  replicas: 5
  datadog: true
ingress:
  path: domain/service
kong:
  routes: [GET,PUT]
hazelcast:
  enabled: true
labels:
  tags.datadoghq.com/env: development
  tags.datadoghq.com/service: my-service
  tags.datadoghq.com/version: 8675309JG
resources:
  enabled: true
  values:
    requests:
      cpu: 20m
      memory: 128Mi
    limits:
      cpu: 25m
      memory: 256Mi
probe:
  enabled: true
  values:
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 35
    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 35