environment: development
namespace: default
serviceName: my-service
imageTag: abc123
secrets:
  enabled: true
  values: [KEYCLOAK_PASSWORD, KEYCLOAK_USER, POSTGRES_DB, KC_DB_URL, POSTGRES_PASSWORD, POSTGRES_USER ] 
  #VALID VALUES - services, tools
  applicationType: services
configmap:
  enabled: true
  values:
    ASPNETCORE_ENVIRONMENT: Development
deployment:
  replicas: 1  
ingress:
  path: domain/service
kong:
  routes: [GET,PUT]