{{if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
data:
{{- toYaml .Values.configmap.values | nindent 2 }}
{{- end }}