{{if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
data:
{{- toYaml .Values.configmap.values | nindent 2 }}
{{- end }}
{{- if .Values.kafka.enabled }}
  KAFKA_BOOTSTRAP: {{ .Values.kafka.server}}
  KAFKA_CA_CERT_PATH: /usr/secrets/kafka/certs/ca.crt
  KAFKA_USER_CERT_PATH: /usr/secrets/kafka/certs/user.crt
  KAFKA_USER_KEY_CERT_PATH: /usr/secrets/kafka/certs/user.key
{{- end }}