{{if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
data:
{{- range $k := $.Values.secrets.values }}
  {{$k}}: <path:argo/data/{{$.Values.environment}}/{{$.Values.secrets.applicationType}}/{{$.Values.secrets.serviceName}}#{{$k}}>
{{- end }}
{{- end }}