apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
{{- if .Values.hazelcast.enabled }}
  - name: hazelcast
    port: 5701
    targetPort: 5701
{{- end }}
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Values.serviceName }}
  type: ClusterIP